---
- name: download puppetlabs rpm
  shell: curl -OR https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
  args:
    chdir: /tmp
    creates: /tmp/puppetlabs-release-pc1-el-6.noarch.rpm

- name: install puppet collections rpm repo
  become: yes
  yum:
    name: /tmp/puppetlabs-release-pc1-el-6.noarch.rpm

- name: install puppet-agent
  become: yes
  with_items:
    - puppet-agent
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
